apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: dolibarr
  name: dolibarr
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: dolibarr
    spec:
      containers:
      - image: mazzyst/dolibarr
        name: dolibarr
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
